package ibus

const IBUS_DEVICE_RADIO = 0x68
const IBUS_DEVICE_BOARD_MONITOR_BUTTONS = 0xf0
const IBUS_DEVICE_IKE = 0x80
const IBUS_DEVICE_MFW = 0x50
const IBUS_DEVICE_NAV_COMPUTER = 0x30
const IBUS_DEVICE_PARK_DISTANCE = 0x60
const IBUS_DEVICE_LIGHT_CONTROL = 0xbf
const IBUS_DEVICE_NAV_LOCATION = 0xd0
const IBUS_DEVICE_BROADCAST = 0xff
const IBUS_DEVICE_CDPLAYER = 0x18

var (
	CdPlayer = &Device_CdPlayer{}
)
